name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - run: echo "The repository has been cloned to the runner."
      - name: List files in the repository
      - run: ls ${{github.workspace}}